FROM postgres:11
LABEL maintainer="M. Edward (Ed) Borasky <znmeb@znmeb.net>"

# Install apt packages
RUN apt-get update \
  && apt-get install -qqy --no-install-recommends \
    postgresql-11-postgis-2.5 \
    postgresql-11-postgis-2.5-scripts \
    postgresql-11-pgrouting \
  && apt-get clean

# set up automatic restores
COPY Backups /Backups
COPY Backups/*.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/*.sh
