FROM docker.io/dpage/pgadmin4:latest
LABEL maintainer="M. Edward (Ed) Borasky <ed.borasky@hackoregon.org>"
# documentation: https://hub.docker.com/r/dpage/pgadmin4/

# add the servers.json
COPY ./pgadmin4-config-files/servers.json /pgadmin4
